logging:
  level:
    ROOT: ERROR
    net.airuima: INFO

spring:
  jackson:
    serialization:
      indent-output: true
  main:
    allow-bean-definition-overriding: true
  cloud:
    consul:
      discovery:
        prefer-ip-address: true
      host: consul
      port: 8500
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://mysql:3306/demo?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: Ruima@(kKJQ5ThBicF/X8p4b61ddg==)
    password: Ruima@(WGL77m8oE2dsPiF1U4YzPUtK2VaWDRGI)
    hikari:
      poolName: Hikari
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
      # 连接池中连接最长空闲时间, ms
      idle-timeout: 60000
      max-lifetime: 60000
      connection-timeout: 60000
      connection-test-query: select 1
      connection-init-sql: select 2
      maximum-pool-size: 20
      #多少毫秒检测一次连接泄露.
      leak-detection-threshold: 60000
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    database: MYSQL
    show-sql: false
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.enable_lazy_load_no_trans: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: true
      hibernate.cache.region.factory_class: com.hazelcast.hibernate.HazelcastCacheRegionFactory
      hibernate.cache.hazelcast.instance_name: demo_mes
      hibernate.cache.use_minimal_puts: true
      hibernate.cache.hazelcast.use_lite_member: true
      hibernate.session_factory.statement_inspector: net.airuima.interceptor.JpaInterceptor
      hibernate.session_factory.interceptor: net.airuima.interceptor.EntityLogInterceptor
  liquibase:
    contexts: prod
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  rabbitmq:
    username: guest
    password: guest
    host: rabbitmq
    port: 5672
    publisher-returns: true
    virtual-host: /zuul
  data:
    redis:
      host: redis
      port: 6379
      password: Ruima@2011
      jedis:
        pool:
          max-active: 512
          max-idle: 100
          max-wait: 100000
          min-idle: 10
      timeout: 100000
      database: 0
server:
  port: 30001
  max-http-request-header-size: 1024000000

#是否启动注册权限
register-auth: ${REGISTER_AUTH:true}

#是否启用微服务模式
micro-mode: ${MICRO_MODE:true}

#是否开启权限
authority-mode: ${AUTHORITY_MODE:true}

#功能配置
function:
  control: true
