logging:
  level:
    ROOT: WARN
    net.airuima: INFO

spring:
  jackson:
    serialization:
      indent-output: true
  main:
    allow-bean-definition-overriding: true
  cloud:
    consul:
      discovery:
        prefer-ip-address: true
        heartbeat:
          enabled: true
      host: localhost
      port: 8500
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://59.110.92.186:3306/demo?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: root
    password: Linktel1234#
    hikari:
      poolName: Hikari
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
      connection-test-query: select 1
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    database: MYSQL
    show-sql: false
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.enable_lazy_load_no_trans: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: true
      hibernate.cache.region.factory_class: com.hazelcast.hibernate.HazelcastCacheRegionFactory
      hibernate.cache.hazelcast.instance_name: demo
      hibernate.cache.use_minimal_puts: true
      hibernate.cache.hazelcast.use_lite_member: true
      hibernate.session_factory.statement_inspector: net.airuima.interceptor.JpaInterceptor
      hibernate.session_factory.interceptor: net.airuima.interceptor.EntityLogInterceptor
  liquibase:
    contexts: dev
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
  #    publisher-returns: true
  #    virtual-host: /zuul
  data:
    redis:
      host: localhost
      port: 6379
      password:
      jedis:
        pool:
          max-active: 512
          max-idle: 100
          max-wait: 100000
          min-idle: 10
      timeout: 100000
      database: 0
server:
  port: 30001
  max-http-request-header-size: 1024000000

#是否启动注册权限
register-auth: ${REGISTER_AUTH:false}

#是否启用微服务模式
micro-mode: ${MICRO_MODE:false}

#是否开启权限
authority-mode: ${AUTHORITY_MODE:false}

#功能配置
function:
  control: false

#租户
tenant: false
